return {
    gb811s2 = {
        spawnName = 'gb811s2',
        name = '811 S2',
        brand = 'Pfister', 
        model = 'gb811s2',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gb811s2`,
    },
    gbadmiral = {
        spawnName = 'gbadmiral',
        name = 'Admiral',
        brand = 'Dundreary', 
        model = 'gbadmiral',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbadmiral`,
    },
    gbargento7f = {
        spawnName = 'gbargento7f',
        name = 'Argento 7F',
        brand = 'Obey', 
        model = 'gbargento7f',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbargento7f`,
    },
    gbbanshees = {
        spawnName = 'gbbanshees',
        name = 'Banshee S',
        brand = 'Bravado', 
        model = 'gbbanshees',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbbanshees`,
    },
    gbbisonhf = {
        spawnName = 'gbbisonhf',
        name = 'Bison HF',
        brand = 'Bravado', 
        model = 'gbbisonhf',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbbisonhf`,
    },
    gbbisonstx = {
        spawnName = 'gbbisonstx',
        name = 'Bison STX',
        brand = 'Bravado', 
        model = 'gbbisonstx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbbisonstx`,
    },
    gbboxboy = {
        spawnName = 'gbboxboy',
        name = 'Boxboy',
        brand = 'Brute', 
        model = 'gbboxboy',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbboxboy`,
    },
    gbboxboyft = {
        spawnName = 'gbboxboyft',
        name = 'Boxboy Food Truck',
        brand = 'Brute', 
        model = 'gbboxboyft',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbboxboyft`,
    },
    gbbriosof = {
        spawnName = 'gbbriosof',
        name = 'Brioso Fulmine',
        brand = 'Grotti', 
        model = 'gbbriosof',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbbriosof`,
    },
    gbclubxr = {
        spawnName = 'gbclubxr',
        name = 'Club XR',
        brand = 'BF', 
        model = 'gbclubxr',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbclubxr`,
    },
    gbcometcl = {
        spawnName = 'gbcometcl',
        name = 'Comet Classic',
        brand = 'Pfister', 
        model = 'gbcometcl',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbcometcl`,
    },
    gbcomets1t = {
        spawnName = 'gbcomets1t',
        name = 'Comet S1 Turbo',
        brand = 'Pfister', 
        model = 'gbcomets1t',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbcomets1t`,
    },
    gbcomets2r = {
        spawnName = 'gbcomets2r',
        name = 'Comet S2R',
        brand = 'Pfister', 
        model = 'gbcomets2r',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbcomets2r`,
    },
    gbcomets2rc = {
        spawnName = 'gbcomets2rc',
        name = 'Comet S2R C',
        brand = 'Pfister', 
        model = 'gbcomets2rc',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbcomets2rc`,
    },
    gbdominatorgsx = {
        spawnName = 'gbdominatorgsx',
        name = 'Dominator GSX',
        brand = 'Vapid', 
        model = 'gbdominatorgsx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbdominatorgsx`,
    },
    gbemerussb1 = {
        spawnName = 'gbemerussb1',
        name = 'Emerus SB1',
        brand = 'Progen', 
        model = 'gbemerussb1',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbemerussb1`,
    },
    gbemsbisonstx = {
        spawnName = 'gbemsbisonstx',
        name = 'Bison STX Ambolance',
        brand = 'Bravado', 
        model = 'gbemsbisonstx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbemsbisonstx`,
    },
    gbemsesperta = {
        spawnName = 'gbemsesperta',
        name = 'Esperta Ambulance',
        brand = 'Bravado', 
        model = 'gbemsesperta',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbemsesperta`,
    },
    gbeon = {
        spawnName = 'gbeon',
        name = 'Eon',
        brand = 'Coil', 
        model = 'gbeon',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbeon`,
    },
    gbesperta = {
        spawnName = 'gbesperta',
        name = 'Esperta',
        brand = 'Bravado', 
        model = 'gbesperta',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbesperta`,
    },
    gbfirevoyager = {
        spawnName = 'gbfirevoyager',
        name = 'Voyager Fire Truck',
        brand = 'MTL', 
        model = 'gbfirevoyager',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbfirevoyager`,
    },
    gbgresleystx = {
        spawnName = 'gbgresleystx',
        name = 'Gresley STX',
        brand = 'Bravado', 
        model = 'gbgresleystx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbgresleystx`,
    },
    gbhades = {
        spawnName = 'gbhades',
        name = 'Hades',
        brand = 'Dundreary',
        model = 'gbhades',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbhades`,
    },
    gbharmann = {
        spawnName = 'gbharmann',
        name = 'Harmann',
        brand = 'Benefactor',
        model = 'gbharmann',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbharmann`,
    },
    gbimpaler = {
        spawnName = 'gbimpaler',
        name = 'Imapaler',
        brand = 'Declasse',
        model = 'gbimpaler',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbimpaler`,
    },
    gbirisz = {
        spawnName = 'gbirisz',
        name = 'Iris Z',
        brand = 'Bollokan', 
        model = 'gbirisz',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbirisz`,
    },
    gbissimetro = {
        spawnName = 'gbissimetro',
        name = 'Issi Metro',
        brand = 'Weeny',
        model = 'gbissimetro',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbissimetro`,
    },
    gbkomodagt = {
        spawnName = 'gbkomodagt',
        name = 'Komoda GT',
        brand = 'Lampadati', 
        model = 'gbkomodagt',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbkomodagt`,
    },
    gblod4 = {
        spawnName = 'gblod4',
        name = 'LOD 4',
        brand = 'Coil', 
        model = 'gblod4',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gblod4`,
    },
    gbmilano = {
        spawnName = 'gbmilano',
        name = 'Milano',
        brand = 'Grotti', 
        model = 'gbmilano',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbmilano`,
    },
    gbmogulrs = {
        spawnName = 'gbmogulrs',
        name = 'Mogul RS',
        brand = 'Karin', 
        model = 'gbmogulrs',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbmogulrs`,
    },
    gbmojave = {
        spawnName = 'gbmojave',
        name = 'Mojave',
        brand = 'Karin', 
        model = 'gbmojave',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbmojave`,
    },
    gbneonct = {
        spawnName = 'gbneonct',
        name = 'Neon CT',
        brand = 'Pfister', 
        model = 'gbneonct',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbneonct`,
    },
    gbnexusrr = {
        spawnName = 'gbnexusrr',
        name = 'Nesus RR',
        brand = 'Dinka', 
        model = 'gbnexusrr',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbnexusrr`,
    },
    gbpolbisonhf = {
        spawnName = 'gbpolbisonhf',
        name = 'Bison HF Police',
        brand = 'Bravado', 
        model = 'gbpolbisonhf',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolbisonhf`,
    },
    gbpolbisonstx = {
        spawnName = 'gbpolbisonstx',
        name = 'Bison STX Police',
        brand = 'Bravado',
        model = 'gbpolbisonstx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolbisonstx`,
    },
    gbpolcometcl = {
        spawnName = 'gbpolcometcl',
        name = 'Comet Classic Police',
        brand = 'Pfister', 
        model = 'gbpolcometcl',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolcometcl`,
    },
    gbpolcomets2r = {
        spawnName = 'gbpolcomets2r',
        name = 'Comet S2R Police',
        brand = 'Pfister', 
        model = 'gbpolcomets2r',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolcomets2r`,
    },
    gbpoldominatorgsx = {
        spawnName = 'gbpoldominatorgsx',
        name = 'Dominator GSX Police',
        brand = 'Vapid',
        model = 'gbpoldominatorgsx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpoldominatorgsx`,
    },
    gbpolprospero = {
        spawnName = 'gbpolprospero',
        name = 'Prospero Police',
        brand = 'Pegassi', 
        model = 'gbpolprospero',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolprospero`,
    },
    gbpolsolace = {
        spawnName = 'gbpolsolace',
        name = 'Solace Police',
        brand = 'Dewbauchee', 
        model = 'gbpolsolace',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolsolace`,
    },
    gbpolstanierle = {
        spawnName = 'gbpolstanierle',
        name = 'Stainer LE Police',
        brand = 'Vapid',
        model = 'gbpolstanierle',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolstanierle`,
    },
    gbpolstarlight = {
        spawnName = 'gbpolstarlight',
        name = 'Starlight Police',
        brand = 'Vulcar', 
        model = 'gbpolstarlight',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolstarlight`,
    },
    gbpolsultanrsx = {
        spawnName = 'gbpolsultanrsx',
        name = 'Sultan RSX Police',
        brand = 'Karin',
        model = 'gbpolsultanrsx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolsultanrsx`,
    },
    gbpoltahomagt = {
        spawnName = 'gbpoltahomagt',
        name = 'Tahoma GT Police',
        brand = 'Declasse', 
        model = 'gbpoltahomagt',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpoltahomagt`,
    },
    gbpoltr3s = {
        spawnName = 'gbpoltr3s',
        name = 'TR3-S Police',
        brand = 'Progen', 
        model = 'gbpoltr3s',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpoltr3s`,
    },
    gbpolturismogt = {
        spawnName = 'gbpolturismogt',
        name = 'Turismo GT Police',
        brand = 'Grotti',
        model = 'gbpolturismogt',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbpolturismogt`,
    },
    gbprospero = {
        spawnName = 'gbprospero',
        name = 'Prospero',
        brand = 'Pegassi', 
        model = 'gbprospero',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbprospero`,
    },
    gbraidillon = {
        spawnName = 'gbraidillon',
        name = 'Raidillon',
        brand = 'Toundra', 
        model = 'gbraidillon',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbraidillon`,
    },
    gbronin = {
        spawnName = 'gbronin',
        name = 'Ronin',
        brand = 'Emperor', 
        model = 'gbronin',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbronin`,
    },
    gbsapphire = {
        spawnName = 'gbsapphire',
        name = 'Sapphire',
        brand = 'Enus', 
        model = 'gbsapphire',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbsapphire`,
    },
    gbschlagenr = {
        spawnName = 'gbschlagenr',
        name = 'Schlagen-R',
        brand = 'Benefactor', 
        model = 'gbschlagenr',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbschlagenr`,
    },
    gbschlagensp = {
        spawnName = 'gbschlagensp',
        name = 'Schlagen-SP',
        brand = 'Benefactor',
        model = 'gbschlagensp',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbschlagensp`,
    },
    gbschrauber = {
        spawnName = 'gbschrauber',
        name = 'Schrauber',
        brand = 'Benefactor', 
        model = 'gbschrauber',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbschrauber`,
    },
    gbschwartzers = {
        spawnName = 'gbschwartzers',
        name = 'Schwartzer S',
        brand = 'Benefactor', 
        model = 'gbschwartzers',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbschwartzers`,
    },
    gbsentinelgts = {
        spawnName = 'gbsentinelgts',
        name = 'Senrinel GTS',
        brand = 'Ubermacht', 
        model = 'gbsentinelgts',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbsentinelgts`,
    },
    gbsidewinder = {
        spawnName = 'gbsidewinder',
        name = 'Sidewinder',
        brand = 'Maxwell', 
        model = 'gbsidewinder',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbsidewinder`,
    },
    gbsolace = {
        spawnName = 'gbsolace',
        name = 'Solace',
        brand = 'Dewbauchee', 
        model = 'gbsolace',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbsolace`,
    },
    gbsolacev = {
        spawnName = 'gbsolacev',
        name = 'Solace Vitesse',
        brand = 'Dewbauchee', 
        model = 'gbsolacev',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbsolacev`,
    },
    gbstanierle = {
        spawnName = 'gbstanierle',
        name = 'Stainer LE',
        brand = 'Vapid',
        model = 'gbstanierle',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbstanierle`,
    },
    gbstarlight = {
        spawnName = 'gbstarlight',
        name = 'Starlight',
        brand = 'Vulcar', 
        model = 'gbstarlight',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbstarlight`,
    },
    gbsultanrsx = {
        spawnName = 'gbsultanrsx',
        name = 'Sultan RSX',
        brand = 'Karin', 
        model = 'gbsultanrsx',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbsultanrsx`,
    },
    gbtahomagt = {
        spawnName = 'gbtahomagt',
        name = 'Tahoma GT',
        brand = 'Declasse',
        model = 'gbtahomagt',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtahomagt`,
    },
    gbtaxiargento7f = {
        spawnName = 'gbtaxiargento7f',
        name = 'Argento 7F Taxi',
        brand = 'Obey', 
        model = 'gbtaxiargento7f',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtaxiargento7f`,
    },
    gbtaxieon = {
        spawnName = 'gbtaxieon',
        name = 'Eon Taxi',
        brand = 'Coil',
        model = 'gbtaxieon',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtaxieon`,
    },
    gbtaxistanierle = {
        spawnName = 'gbtaxistanierle',
        name = 'Stainer LE Taxi',
        brand = 'Vapid',
        model = 'gbtaxistanierle',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtaxistanierle`,
    },
    gbtaxistarlight = {
        spawnName = 'gbtaxistarlight',
        name = 'Starlight Taxi',
        brand = 'Vulcar',
        model = 'gbtaxistarlight',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtaxistarlight`,
    },
    gbtenfr = {
        spawnName = 'gbtenfr',
        name = 'Tenf R',
        brand = 'Obey', 
        model = 'gbtenfr',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtenfr`,
    },
    gbterrorizer = {
        spawnName = 'gbterrorizer',
        name = 'Terrorizer',
        brand = 'HVY', 
        model = 'gbterrorizer',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbterrorizer`,
    },
    gbtr3s = {
        spawnName = 'gbtr3s',
        name = 'TR3-S',
        brand = 'Progen', 
        model = 'gbtr3s',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbtr3s`,
    },
    gbturismogt = {
        spawnName = 'gbturismogt',
        name = 'Turismo GT',
        brand = 'Grotti',
        model = 'gbturismogt',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbturismogt`,
    },
    gbturismogts = {
        spawnName = 'gbturismogts',
        name = 'Turismo GTS',
        brand = 'Grotti',
        model = 'gbturismogts',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbturismogts`,
    },
    gbvivant = {
        spawnName = 'gbvivant',
        name = 'Vivant',
        brand = 'Bordeaux', 
        model = 'gbvivant',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvivant`,
    },
    gbvivantgrb = {
        spawnName = 'gbvivantgrb',
        name = 'Vivant GRB',
        brand = 'Bordeaux', 
        model = 'gbvivantgrb',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvivantgrb`,
    },
    gbvoyager = {
        spawnName = 'gbvoyager',
        name = 'Voyager 6x4-T',
        brand = 'MTL', 
        model = 'gbvoyager',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvoyager`,
    },
    gbvoyager2 = {
        spawnName = 'gbvoyager2',
        name = 'Voyager 4x2-T ',
        brand = 'MTL', 
        model = 'gbvoyager2',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvoyager2`,
    },
    gbvoyagerb = {
        spawnName = 'gbvoyagerb',
        name = 'Voyager 6x4-B',
        brand = 'MTL', 
        model = 'gbvoyagerb',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvoyagerb`,
    },
    gbvoyagerb2 = {
        spawnName = 'gbvoyagerb2',
        name = 'Voyager 4x2-B',
        brand = 'MTL', 
        model = 'gbvoyagerb2',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvoyagerb2`,
    },
    gbvoyagerg = {
        spawnName = 'gbvoyagerg',
        name = 'Voyager Trash Truck',
        brand = 'MTL', 
        model = 'gbvoyagerg',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvoyagerg`,
    },
    gbvoyagerh = {
        spawnName = 'gbvoyagerh',
        name = 'Voyager 6x2-H',
        brand = 'MTL', 
        model = 'gbvoyagerh',
        price = 5000,
        category = 'nil',
        type = 'automobile',
        hash = `gbvoyagerh`,
    },
}